### ISSUE TITLE
Pores Annotation

### ISSUE THREAD

**Issue by prog96** [MIC-DKFZ/napari-sam#12]
Hello,

This tool looks amazing and I would like to get to know more about it and apply it in the future work. 

Right now I would like to segment defects like pores/cracks in manufactured items as shown below:
![image](https://github.com/MIC-DKFZ/napari-sam/assets/74073398/b810030c-881e-4924-92e6-e7d673cd917a)

However, when I clicked on one of the pores it did not segment properly.
![image](https://github.com/MIC-DKFZ/napari-sam/assets/74073398/b20dae50-bd5e-457f-bc1b-527e03b1c3c0)

I am not sure where the problem comes from but it would be great if you could help me with this! Thank you in advance!

**Comment by Karol-G** [comment]
Hey @prog96 ,

I am not entirely sure what you want the final segmentation to look like as I never worked with such images before. Could you please show me some ground truth segmentations or reference segmentations created by you so I can get a better understanding?

Best,
Karol

**Comment by prog96** [comment]
The annotated one should look like this:
![image](https://github.com/MIC-DKFZ/napari-sam/assets/74073398/3cc2c282-4ed9-45e0-95af-7c4d3d493eba)

I am not sure if SAM is applicable on such data segmentation.

**Comment by Karol-G** [comment]
I think SAM should work on such data. What you can try is to place one positive marker on each of the two spots and some negative markers around it. Alternatively, you could also try to use the bounding box mode and create a bounding box for the two spots.

If you upload the raw image then I can also try my luck if you want :)

**Comment by prog96** [comment]
I have tried the first method by placing the positive and negative markers but it did not work that well. Ideally, it would be best to annotate the pores just by placing only one positive marker, without any negative marker. 

Here is the image:
![sample image](https://github.com/MIC-DKFZ/napari-sam/assets/74073398/b9c982db-b5c4-4812-9dd7-dc9c37c135db)

**Comment by Karol-G** [comment]
I also tested a bit with your image and it really seems that SAM is unable to get good results here. To me, it seems that the resolution of the pores are too small for SAM. Sorry that I am unable to help you here with this :/

**Comment by prog96** [comment]
No worries. Thank you for trying that out! :)
