### ISSUE TITLE
Update dependencies and imports

### ISSUE THREAD

**Issue by goanpeca** [MIC-DKFZ/napari-sam#16]
Hello team!

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending not to depend directly on PyQt5 or PySide2 to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

The files using `PyQt5` instead of `qtpy` are listed here -> https://github.com/search?q=repo%3AMIC-DKFZ%2Fnapari-sam%20pyqt5&type=code

Is there a reason you need PyQt5 explicitly? Could these imports be updated to use `qtpy` for the next release?

--

Also it seems some dependencies are not currently included:
- pytorch>=1.7 
- torchvision>=0.8
- superqt

Could these dependencies be updated for the next release?

Thanks! 🚀

**Comment by Karol-G** [comment]
Hey @goanpeca,

I did some cleanup and was able to remove the PyQt5 dependency. I did not include pytorch and torchvision in the dependencies as I state in the readme that they should be installed by the user. Based on my experience, including pytorch in the requirements often leads to issues.

Best,
Karol
