### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by aloboa** [MIC-DKFZ/napari-sam#21]
Just installed by following directions, but once I select the plugin, I get:
`RuntimeError: Failed to import command at 'napari_sam._widget:SamWidget': No module named 'torch'`

I think the problem is that your directions start by:
"Please follow the instructions here to install both PyTorch and TorchVision dependencies."
and probably the *here* is missing a link (I understood PyTorch and TorchVision dependencies would
be installed by following your directions.
Ir would great help for naif users to actually have the link.

**Comment by Karol-G** [comment]
The plugin requires python>=3.8, as well as pytorch>=1.7 and torchvision>=0.8.

**Comment by aloboa** [comment]
Seems to have been solved by
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
following
https://pytorch.org/
