### ISSUE TITLE
Unable to read the picture!

### ISSUE THREAD

**Issue by sunmooncode** [MIC-DKFZ/napari-sam#3]
Thank you for your work!
When I opened the Napari, I encountered the following problem:
`WARNING: QOpenGLWidget: Failed to create context
11:41:40 WARNING QOpenGLWidget: Failed to create context
WARNING: QOpenGLWidget: Failed to create context
11:41:40 WARNING QOpenGLWidget: Failed to create context
WARNING: composeAndFlush: QOpenGLContext creation failed
11:41:40 WARNING composeAndFlush: QOpenGLContext creation failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:40 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:41 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
11:41:57 WARNING composeAndFlush: makeCurrent() failed`

Is there any way to solve it?

**Comment by Karol-G** [comment]
Hey,

it seems that these are only warnings. Are you able to see the image in Napari itself?
Have you installed PyQt5? This is a requirement for Napari.
You can install it with:
`pip install PyQt5`

Best,
Karol

**Comment by sunmooncode** [comment]
When I selected the image to open, it didn't show up.

about pyqt5:
`Requirement already satisfied: pyqt5 in /home/anaconda3/envs/napari/lib/python3.8/site-packages (5.15.9)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in /home/anaconda3/envs/napari/lib/python3.8/site-packages (from pyqt5) (12.12.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /home/anaconda3/envs/napari/lib/python3.8/site-packages (from pyqt5) (5.15.2)`

**Comment by Karol-G** [comment]
Is it a 2D or a 3D image and what is the file format of the image?

**Comment by sunmooncode** [comment]
It's a 2D 'png' image.

**Comment by sunmooncode** [comment]
Can I read images directly in PNG or jpg format, or do I need to convert them?

**Comment by Karol-G** [comment]
There shouldn't be a problem with the format. I will have a look at it in the evening today. Can you maybe upload the image here so I can try to reproduce the error on my side?

**Comment by sunmooncode** [comment]
![000058](https://user-images.githubusercontent.com/86471590/231732640-7221e8ec-89a8-4469-9764-8e3f48bca465.png)

**Comment by Karol-G** [comment]
Hey again,

it worked without a problem on my side.
I recommend to setup a new environemnt in anaconda and reinstalll everything as in [here](https://www.zeit.de/2023/16/mathias-doepfner-axel-springer-interne-dokumente/seite-2). I think it is likely that something in your current python environment is broken, which causes the problem.

![example](https://user-images.githubusercontent.com/3471895/231845065-5f17a3c5-7e00-4039-b049-20355924a6c1.png)

Best,
Karol

**Comment by EnginEren** [comment]
Hi Karol, can you run it **only** with GPU + CUDA ? Is it possible to run it in standard Ubuntu without GPU and Cuda ?
