### ISSUE TITLE
Napari-Sam on colab?

### ISSUE THREAD

**Issue by Meddebma** [MIC-DKFZ/napari-sam#4]
Hi, 

I have no cuda support on my old macbook, can I run napari-sam on goolge colab? 

Thanks

**Comment by Karol-G** [comment]
Hi,

I don't think so. Napari does not work on colab.
However, there is a SAM demo created by someone else for colab. Maybe that fits you needs?

https://colab.research.google.com/github/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb

Best,
Karol

**Comment by Meddebma** [comment]
Thank you very much Karol! 
Best,
Aymen
