### ISSUE TITLE
Exposing Segment Anything Parameters

### ISSUE THREAD

**Issue by unidesigner** [MIC-DKFZ/napari-sam#5]
There are a couple of parameters for Segment Anything, such as `pred_iou_thresh`, `stability_score_thresh`, `box_nms_thresh`,`points_per_side` etc. I think it would be quite useful, especially in the segment everything case, to expose them to the user e.g. via an an additional tab. Would it be possible to add that?

**Comment by Karol-G** [comment]
Took a while until I had time to implement this feature, but it is finally done. It is now possible to change all parameters for SAM when in Everything mode :)

**Comment by unidesigner** [comment]
Great, thanks. I'll test it out soon.
