### ISSUE TITLE
Loading sam_checkpoint problem

### ISSUE THREAD

**Issue by drahmedshaheen** [MIC-DKFZ/napari-sam#6]
The app keeps freezing and not responding when I tried to load the sam_checkpoint
I don't know if this issue is because SAM doesn't support m1 "mps" or not
Please add the option to use CPU if the app working on mac m1 or m2 till SAM supports mps 

best regards

**Comment by drahmedshaheen** [comment]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/anaconda3/envs/ai/lib/python3.10/site-packages/napari_sam/_widget.py:329, in SamWidget._load_model(self=<napari_sam._widget.SamWidget object>)
    327 model_types = list(sam_model_registry.keys())
    328 model_type = model_types[self.cb_model_type.currentIndex()]
--> 329 self.sam_model = sam_model_registry[model_type](
        model_type = 'default'
        self.sam_model = None
        self = <napari_sam._widget.SamWidget object at 0x7fdf34145d80>
        sam_model_registry[model_type] = <function build_sam_vit_h at 0x7fdf341465f0>
        sam_model_registry = {'default': <function build_sam_vit_h at 0x7fdf341465f0>, 'vit_h': <function build_sam_vit_h at 0x7fdf341465f0>, 'vit_l': <function build_sam_vit_l at 0x7fdf3659f7f0>, 'vit_b': <function build_sam_vit_b at 0x7fdf3667d2d0>}
    330     get_weights_path(model_type)
    331 )
    332 self.sam_model.to(self.device)
    333 self.sam_predictor = SamPredictor(self.sam_model)

File ~/anaconda3/envs/ai/lib/python3.10/site-packages/segment_anything/build_sam.py:15, in build_sam_vit_h(checkpoint=PosixPath('/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'))
     14 def build_sam_vit_h(checkpoint=None):
---> 15     return _build_sam(
        checkpoint = PosixPath('/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth')
     16         encoder_embed_dim=1280,
     17         encoder_depth=32,
     18         encoder_num_heads=16,
     19         encoder_global_attn_indexes=[7, 15, 23, 31],
     20         checkpoint=checkpoint,
     21     )

File ~/anaconda3/envs/ai/lib/python3.10/site-packages/segment_anything/build_sam.py:105, in _build_sam(encoder_embed_dim=1280, encoder_depth=32, encoder_num_heads=16, encoder_global_attn_indexes=[7, 15, 23, 31], checkpoint=PosixPath('/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'))
    103 if checkpoint is not None:
    104     with open(checkpoint, "rb") as f:
--> 105         state_dict = torch.load(f)
        f = <_io.BufferedReader name='/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'>
    106     sam.load_state_dict(state_dict)
    107 return sam

File ~/anaconda3/envs/ai/lib/python3.10/site-packages/torch/serialization.py:797, in load(f=<_io.BufferedReader name='/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'>, map_location=None, pickle_module=<module 'pickle' from '/Users/ahmedshaheen/anaconda3/envs/ai/lib/python3.10/pickle.py'>, weights_only=False, **pickle_load_args={'encoding': 'utf-8'})
    792 if _is_zipfile(opened_file):
    793     # The zipfile reader is going to advance the current file position.
    794     # If we want to actually tail call to torch.jit.load, we need to
    795     # reset back to the original position.
    796     orig_position = opened_file.tell()
--> 797     with _open_zipfile_reader(opened_file) as opened_zipfile:
        opened_file = <_io.BufferedReader name='/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'>
    798         if _is_torchscript_zip(opened_zipfile):
    799             warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
    800                           " dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to"
    801                           " silence this warning)", UserWarning)

File ~/anaconda3/envs/ai/lib/python3.10/site-packages/torch/serialization.py:283, in _open_zipfile_reader.__init__(self=<torch.serialization._open_zipfile_reader object>, name_or_buffer=<_io.BufferedReader name='/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'>)
    282 def __init__(self, name_or_buffer) -> None:
--> 283     super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
        torch._C.PyTorchFileReader = <class 'torch.PyTorchFileReader'>
        name_or_buffer = <_io.BufferedReader name='/Users/ahmedshaheen/.cache/napari-segment-anything/sam_vit_h_4b8939.pth'>
        torch._C = <module 'torch._C' from '/Users/ahmedshaheen/anaconda3/envs/ai/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so'>

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Karol-G** [comment]
I do not have a mac so it won't be possible to reproduce or fix the problem, sorry. Have you installed the pytorch cpu only version?

**Comment by drahmedshaheen** [comment]
I did so and it worked, thank you so much

**Comment by drahmedshaheen** [comment]
> I do not have a mac so it won't be possible to reproduce or fix the problem, sorry. Have you installed the Pytorch CPU only version?

I installed the mps Pytorch version, the problem was due to corrupted check point files and it was solved after manually downloading and replacing the file

**Comment by Karol-G** [comment]
Good to know! :)
