### ISSUE TITLE
The results seem to be wrong

### ISSUE THREAD

**Issue by YaoZhang93** [MIC-DKFZ/napari-sam#8]
Hi,

Thanks for your excellent work in making SAM easy to use. I tried a CT volume with the plugin in the "Everything mode"but the results seem to be wrong. Did I miss something?
![image](https://user-images.githubusercontent.com/58619665/233835100-409d06a5-16a4-4c1f-a264-19e9d6a2e9ec.png)

Best,
Yao

**Comment by Karol-G** [comment]
Hey,

The everything segmentation from SAM often does not give good results on medical images, from my experience. It can work quite well on natural images, but for medical images, I recommend the click mode. Also, it is worth adjusting the contrast limits to make relevant regions brighter. From my experience, brighter images work better with SAM than darker ones.

Best,
Karol

**Comment by YaoZhang93** [comment]
Got it. Thanks for your kind suggestion.
